"""First configured project screen (B3a, D-02, RF-014/015/016; Producto §5.1).

Shown only when a key is already configured but no project has been set up
yet (see ``sirius.main`` for the exact gate: ``InitialProjectUseCase.is_configured()``,
never a direct repository query). Like every other presentation module, it
only ever talks to ``sirius.application.initial_project.InitialProjectUseCase``
— never ``ProjectRepository``, SQLAlchemy, or SQLite directly (AGENTS.md: "No
accedas a SQLite ... desde la interfaz").

The greeting is deterministic, centralized text — never generated by an LLM
— and reuses ``sirius.domain.identity.INITIAL_IDENTITY_NAME`` instead of
duplicating "Sirius" as a separate constant.
"""

from __future__ import annotations

from collections.abc import Callable

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QFormLayout,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QVBoxLayout,
    QWidget,
)

from sirius.application.initial_project import (
    InitialProjectAlreadyConfiguredError,
    InitialProjectUseCase,
    InvalidInitialProjectDataError,
)
from sirius.domain.identity import INITIAL_IDENTITY_NAME
from sirius.infrastructure.logging import get_logger

_logger = get_logger(__name__)

GREETING_TEXT = (
    f"Soy {INITIAL_IDENTITY_NAME}, tu compañero personal de creación e ingeniería.\n\n"
    "Trabajo siempre alrededor de un único proyecto activo. Para empezar, crea o "
    "describe el proyecto en el que vamos a trabajar."
)

_GENERIC_ERROR_TEXT = "No se pudo crear el proyecto. Inténtalo de nuevo."


class InitialProjectWindow(QMainWindow):
    """Primera creación del proyecto activo: únicamente nombre y objetivo.

    Emits ``created`` exactly once, after the project has been persisted as
    the single active project. The caller (``sirius.main``) is responsible
    for showing the main conversation window and closing this one.
    """

    created = Signal()

    def __init__(
        self,
        initial_project_use_case: InitialProjectUseCase,
        *,
        show_warning: Callable[[str, str], None] | None = None,
    ) -> None:
        super().__init__()
        self._initial_project_use_case = initial_project_use_case
        self._show_warning = show_warning or self._default_show_warning
        self._is_busy = False

        self.setWindowTitle("Sirius 0.1 — Primer proyecto")
        self.resize(560, 380)

        title = QLabel("Antes de empezar")
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        title_font = title.font()
        title_font.setBold(True)
        title_font.setPointSize(title_font.pointSize() + 2)
        title.setFont(title_font)

        greeting_label = QLabel(GREETING_TEXT)
        greeting_label.setWordWrap(True)

        self.name_input = QLineEdit()
        self.name_input.setPlaceholderText("Nombre del proyecto")
        self.name_input.returnPressed.connect(self._handle_create_clicked)

        self.objective_input = QLineEdit()
        self.objective_input.setPlaceholderText("Objetivo del proyecto")
        self.objective_input.returnPressed.connect(self._handle_create_clicked)

        self.create_button = QPushButton("Crear proyecto")
        self.create_button.clicked.connect(self._handle_create_clicked)
        self.create_button.setDefault(True)
        self.create_button.setAutoDefault(True)

        self.status_label = QLabel("")
        self.status_label.setWordWrap(True)

        form = QFormLayout()
        form.addRow("Nombre:", self.name_input)
        form.addRow("Objetivo:", self.objective_input)

        container = QWidget()
        layout = QVBoxLayout(container)
        layout.addWidget(title)
        layout.addWidget(greeting_label)
        layout.addLayout(form)
        layout.addWidget(self.create_button)
        layout.addWidget(self.status_label)
        layout.addStretch()
        self.setCentralWidget(container)

        self.name_input.setFocus()

    def _default_show_warning(self, title: str, text: str) -> None:
        QMessageBox.warning(self, title, text)

    def _set_controls_enabled(self, enabled: bool) -> None:
        self.name_input.setEnabled(enabled)
        self.objective_input.setEnabled(enabled)
        self.create_button.setEnabled(enabled)

    def _handle_create_clicked(self) -> None:
        if self._is_busy:
            return

        name = self.name_input.text()
        objective = self.objective_input.text()
        if not name.strip() or not objective.strip():
            self._show_warning(
                "Faltan datos", "Escribe un nombre y un objetivo antes de continuar."
            )
            return

        self._is_busy = True
        self._set_controls_enabled(False)
        self.status_label.setText("")

        try:
            self._initial_project_use_case.create_initial_project(name, objective)
        except InvalidInitialProjectDataError as exc:
            self.status_label.setText(str(exc))
        except InitialProjectAlreadyConfiguredError as exc:
            self.status_label.setText(str(exc))
        except Exception as exc:
            _logger.error("No se pudo crear el proyecto inicial (%s)", type(exc).__name__)
            self.status_label.setText(_GENERIC_ERROR_TEXT)
        else:
            # Deliberately stays busy/disabled: the caller closes this window
            # right after `created`, so re-enabling now-obsolete controls
            # would be pointless (same pattern as MainWindow's restore
            # success) and this also guards against a double submission
            # reaching the use case a second time before the window closes.
            self.created.emit()
            return

        self._is_busy = False
        self._set_controls_enabled(True)
