"""add decision supersession

Revision ID: 05559a954593
Revises: 938fc6ac868c
Create Date: 2026-07-19 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05559a954593'
down_revision: str | Sequence[str] | None = '938fc6ac868c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### link a decision to the decision it explicitly supersedes (B4c,
    # RF-023, PA-013). Purely additive: one nullable, self-referential
    # column on the existing decisions table, no existing table or row is
    # touched, so every previously stored decision and revision is
    # preserved untouched with supersedes_decision_id = NULL (correct: no
    # decision was ever superseded before this migration). A single ALTER
    # TABLE ... ADD COLUMN ... REFERENCES statement is used rather than
    # op.add_column(sa.Column(..., ForeignKey(...))) for the same reason as
    # 810c1563f6c6/6f710ea6c2d2: SQLite understands and enforces it
    # natively (PRAGMA foreign_keys=ON is already set on every connection),
    # avoiding the unsupported two-step "ADD CONSTRAINT" Alembic would
    # otherwise emit for SQLite outside batch mode. ###
    op.execute(
        'ALTER TABLE decisions ADD COLUMN supersedes_decision_id INTEGER '
        'REFERENCES decisions (id)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'supersedes_decision_id')
    # ### end Alembic commands ###
