"""create memory suggestions

Revision ID: 1975a5496c12
Revises: 61be4bb269bf
Create Date: 2026-08-29 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1975a5496c12'
down_revision: str | Sequence[str] | None = '61be4bb269bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### M4 (SIRIUS-ARQ-0.2 §3.3/§3.4/§3.7): a single new table, purely
    # additive — no existing table is touched, so every previously stored
    # row is preserved untouched. No unique index on status (§3.7): several
    # suggestions may be PENDING at once, even of the same subject; the
    # ambiguity, if any, is resolved by the user confirming or rejecting
    # each one, not by a database constraint. ###
    op.create_table(
        'memory_suggestions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'pending', 'confirmed', 'rejected',
                name='memorysuggestionstatus', native_enum=False, length=16,
            ),
            nullable=False,
        ),
        sa.Column('subject_key', sa.Text(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('source_event_id', sa.Integer(), nullable=True),
        sa.Column('resulting_memory_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.ForeignKeyConstraint(['source_event_id'], ['events.id']),
        sa.ForeignKeyConstraint(['resulting_memory_id'], ['memories.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_suggestions')
    # ### end Alembic commands ###
