"""add memory subject_key and project_id

Revision ID: 43406702d62c
Revises: bf0ac43b986b
Create Date: 2026-07-19 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43406702d62c'
down_revision: str | Sequence[str] | None = 'bf0ac43b986b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### add the optional subject/project boundary B4e's precedence and
    # conflict rule (RF-026, DR-011) needs to compare memories of "el mismo
    # asunto" — the memory-side counterpart of the decisions.subject/
    # project_id columns 938fc6ac868c already added. Both columns are
    # purely additive and nullable: no existing table or row is touched, so
    # every previously stored memory is preserved untouched with
    # subject_key = NULL and project_id = NULL (correct — no memory ever
    # declared a subject before this migration, and one that still doesn't
    # never participates in precedence/conflict detection, see
    # sirius.domain.memory's module docstring).
    #
    # project_id uses a single ALTER TABLE ... ADD COLUMN ... REFERENCES
    # statement, the same technique 05559a954593/810c1563f6c6 already used,
    # for the same reason: SQLite understands and enforces it natively
    # (PRAGMA foreign_keys=ON is already set on every connection), avoiding
    # the unsupported two-step "ADD CONSTRAINT" Alembic would otherwise emit
    # for SQLite outside batch mode. ON DELETE SET NULL mirrors
    # EventModel.message_id (810c1563f6c6): deleting a project must never
    # cascade into silently deleting a memory, only detach it from that
    # project boundary. ###
    op.add_column('memories', sa.Column('subject_key', sa.Text(), nullable=True))
    op.execute(
        'ALTER TABLE memories ADD COLUMN project_id INTEGER '
        'REFERENCES projects (id) ON DELETE SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'project_id')
    op.drop_column('memories', 'subject_key')
    # ### end Alembic commands ###
