"""create projects

Revision ID: 5ee754bfb0c2
Revises: c4d8fc9d6f51
Create Date: 2026-07-12 13:00:45.402220

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5ee754bfb0c2'
down_revision: str | Sequence[str] | None = 'c4d8fc9d6f51'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=False),
    sa.Column('next_step', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_projects_single_active', 'projects', ['is_active'], unique=True, sqlite_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_projects_single_active', table_name='projects', sqlite_where=sa.text('is_active = 1'))
    op.drop_table('projects')
    # ### end Alembic commands ###
