"""add category to memories and decisions

Revision ID: 71bb52f6cc2b
Revises: 1975a5496c12
Create Date: 2026-08-29 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '71bb52f6cc2b'
down_revision: str | Sequence[str] | None = '1975a5496c12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### M8 (SIRIUS-ARQ-0.2 §6.1/§8-M8, D7 point 1): two new columns on each
    # of `memories` and `decisions`, purely additive — no existing table or
    # row is touched, so every previously stored memory/decision is
    # preserved untouched. `category_locked` is NOT NULL with a server
    # default of 0/False (same pattern `is_current`/`is_active` already
    # use): every row that predates this migration backfills to
    # `category = NULL`, `category_locked = False`, which is exactly what D7
    # point 4 requires to make it immediately eligible for the retroactive
    # tagging pass. ###
    op.add_column('memories', sa.Column('category', sa.Text(), nullable=True))
    op.add_column(
        'memories',
        sa.Column(
            'category_locked', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column('decisions', sa.Column('category', sa.Text(), nullable=True))
    op.add_column(
        'decisions',
        sa.Column(
            'category_locked', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'category_locked')
    op.drop_column('decisions', 'category')
    op.drop_column('memories', 'category_locked')
    op.drop_column('memories', 'category')
    # ### end Alembic commands ###
