"""create decisions and decision revisions

Revision ID: 938fc6ac868c
Revises: 810c1563f6c6
Create Date: 2026-07-18 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '938fc6ac868c'
down_revision: str | Sequence[str] | None = '810c1563f6c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### create decisions and decision_revisions (B4b, RF-020, PA-011).
    # Purely additive: two brand-new tables, no existing table is touched, so
    # every previously stored row is preserved untouched. ###
    op.create_table(
        'decisions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('subject', sa.Text(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('proposed', 'approved', name='decisionstatus', native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'decision_revisions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('decision_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('source_event_id', sa.Integer(), nullable=True),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_event_id'], ['events.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('decision_id', 'version', name='uq_decision_revisions_decision_version'),
    )
    op.create_index(
        'uq_decision_revisions_single_current_per_decision',
        'decision_revisions',
        ['decision_id'],
        unique=True,
        sqlite_where=sa.text('is_current = 1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_revisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
