"""add memory subject and project

Revision ID: 94418c79da9d
Revises: bf0ac43b986b
Create Date: 2026-07-19 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94418c79da9d'
down_revision: str | Sequence[str] | None = 'bf0ac43b986b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### give a memory the same explicit "asunto"/project identification a
    # decision already carries (B4e, RF-026, DR-011): the minimal persistent
    # addition precedence and conflict detection need to compare memories of
    # the same subject. Both columns are additive and nullable — no existing
    # table or row is touched, so every previously stored memory is
    # preserved untouched with subject_key = NULL and project_id = NULL
    # (correct: no memory declared an explicit subject before this
    # migration, and stays outside precedence/conflict comparison as a
    # result, see sirius.domain.precedence).
    #
    # subject_key is plain text (op.add_column is enough: no constraint to
    # add natively). project_id is a real, enforced foreign key to
    # projects.id — a single ALTER TABLE ... ADD COLUMN ... REFERENCES
    # statement is used instead of op.add_column(sa.Column(...,
    # ForeignKey(...))) for the same reason as 810c1563f6c6/938fc6ac868c/
    # 05559a954593: SQLite understands and enforces it natively (PRAGMA
    # foreign_keys=ON is already set on every connection), avoiding the
    # unsupported two-step "ADD CONSTRAINT" Alembic would otherwise emit for
    # SQLite outside batch mode. ###
    op.add_column('memories', sa.Column('subject_key', sa.Text(), nullable=True))
    op.execute(
        'ALTER TABLE memories ADD COLUMN project_id INTEGER REFERENCES projects (id)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'project_id')
    op.drop_column('memories', 'subject_key')
    # ### end Alembic commands ###
