"""create identities and identity versions

Revision ID: bd39e7e3df5e
Revises: 4022f15cc8df
Create Date: 2026-07-12 16:33:12.189742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bd39e7e3df5e'
down_revision: str | Sequence[str] | None = '4022f15cc8df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('personality_instructions', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'version', name='uq_identity_versions_identity_version')
    )
    op.create_index('uq_identity_versions_single_current_per_identity', 'identity_versions', ['identity_id'], unique=True, sqlite_where=sa.text('is_current = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_identity_versions_single_current_per_identity', table_name='identity_versions', sqlite_where=sa.text('is_current = 1'))
    op.drop_table('identity_versions')
    op.drop_table('identities')
    # ### end Alembic commands ###
