"""add message redaction

Revision ID: bf0ac43b986b
Revises: 05559a954593
Create Date: 2026-07-19 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf0ac43b986b'
down_revision: str | Sequence[str] | None = '05559a954593'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### add message redaction (B4d, RF-025/DR-012: "El mensaje fuente se
    # redacta solo si el usuario lo solicita"). Two changes, both additive
    # or purely relaxing an existing constraint — no existing row's content
    # is touched, so every previously stored message is preserved exactly
    # as it was, with redacted_at = NULL (correct: no message was ever
    # redacted before this migration):
    #
    # 1. messages.redacted_at: a new nullable column, mirroring
    #    events.redacted_at (810c1563f6c6).
    # 2. messages.content: relaxed from NOT NULL to nullable, since a
    #    redacted message's content becomes NULL (SIRIUS-ARQ-0.1 S7.3:
    #    "contenido NULL solo si REDACTADO"). SQLite has no ALTER COLUMN;
    #    batch mode is the only way to relax a NOT NULL constraint, and
    #    necessarily recreates the table under the hood — same technique
    #    f5fb28ed426a already used on this exact table for its unique
    #    constraint. Every row's data (id, content, ...) is copied over
    #    unchanged; nothing is reset or reinterpreted. ###
    op.add_column('messages', sa.Column('redacted_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('content', existing_type=sa.Text(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('content', existing_type=sa.Text(), nullable=False)
    op.drop_column('messages', 'redacted_at')
    # ### end Alembic commands ###
