"""add criticality to memories and decisions

Revision ID: de3545536503
Revises: 71bb52f6cc2b
Create Date: 2026-09-02 23:02:51.624511

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'de3545536503'
down_revision: str | Sequence[str] | None = '71bb52f6cc2b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### M18b (ADR-126, Decisión 1 de la evidencia
    # "filtro-fiel-al-laboratorio"): una sola columna nueva en cada una de
    # `memories`/`decisions`, purely additive — mirrors 71bb52f6cc2b's
    # `category` column exactly, minus `category_locked`: este encargo no
    # introduce clasificación automática, así que no hay nada de qué
    # proteger un candado. NULL en toda fila que predata esta migración,
    # que es exactamente "nadie la ha marcado" (ver `sirius.domain.
    # criticality.Criticality`). ###
    op.add_column('memories', sa.Column('criticality', sa.Text(), nullable=True))
    op.add_column('decisions', sa.Column('criticality', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'criticality')
    op.drop_column('memories', 'criticality')
    # ### end Alembic commands ###
